plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bubbleburst.odyssey'
    compileSdk 34

    defaultConfig {
        applicationId "com.bubbleburst.odyssey"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.8.0'
    implementation 'androidx.core:core:1.13.0'
}
